server:
  port: 9091
  servlet: 
    context-path: /v1
    
    
logging:
  level:
    org.springframework: ERROR
    com.rsystems: DEBUG
  file: /data/urlshortner.log

  
  
spring:            
  datasource:
    url: jdbc:mysql://mysqldb:3306/urlshortner
    username: root
    password: root123               
    
