FROM java:8
LABEL maintainer=“guntassingh@gmail.com”
EXPOSE 9091
ADD target/URLShortener-0.0.1-SNAPSHOT.jar URLShortener-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","URLShortener-0.0.1-SNAPSHOT.jar"]